version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "npm"
      - "dependencies"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies-root:
        patterns:
          - "*"


  - package-ecosystem: "npm"
    directory: "/layers/lambda-powertools"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "npm"
      - "dependencies"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies-powertools-layer:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "github_actions"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: "daily"