openapi: 3.0.0
info:
  version: 1.0.0
  title: Math Operation Service
  description: Service that allows you to do several math operations with simple API calls.
  contact:
    name: Andres Moreno
    email: andres@andmore.dev

tags:
  - name: Operations
    description: Math Operations

servers:
  - url: replace with real url
    description: some base url

x-amazon-apigateway-request-validators:
  Validate body, query string parameters, and headers:
    validateRequestParameters: true
    validateRequestBody: true

x-amazon-apigateway-gateway-responses:
  BAD_REQUEST_BODY:
    statusCode: '400'
    responseTemplates:
      application/json: '{ "message": "$context.error.validationErrorString" }'
  UNAUTHORIZED:
    statusCode: '401'
    responseTemplates:
      application/json: '{ "message": "Unauthorized" }'
  ACCESS_DENIED:
    statusCode: '401'
    responseTemplates:
      application/json: '{ "message": "Unauthorized" }'

paths:
  /addition:
    post:
      summary: Add Numbers
      description: |
        Numbers provided will be added.
      operationId: addition
      tags:
        - Operations
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                number1:
                  type: number
                  maximum: 1000
                  minimum: 0
                number2:
                  type: number
                  maximum: 1000
                  minimum: 0
      responses:
        '200':
          description: Addition done
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    type: number
                  warning:
                    type: string
                    description: Warning when result is greater than 1000
                    enum:
                      - The result is greater than 1000
        '400':
          description: Invalid data provided
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      x-amazon-apigateway-request-validator: Validate body, query string parameters, and headers
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AdditionFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /substraction:
    post:
      summary: Substract Numbers
      description: |
        Numbers provided will be substracted
      operationId: substraction
      tags:
        - Operations
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                number1:
                  type: number
                  maximum: 1000
                  minimum: 0
                number2:
                  type: number
                  maximum: 1000
                  minimum: 0
      responses:
        '200':
          description: Substraction done
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    type: number
                  warning:
                    type: string
                    description: Warning when result is less than -1000
                    enum:
                      - The result is less than -1000
        '400':
          description: Invalid data provided
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      x-amazon-apigateway-request-validator: Validate body, query string parameters, and headers
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SubstractionFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy