AWSTemplateFormatVersion: 2010-09-09
Description: aws-community-day-mx
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  TableName:
    Type: String

Globals:
  Function:
    Tracing: Active
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 128
    Handler: index.handler
    Layers:
      - !Ref LambdaPowertoolsLayer
    Architectures:
      - arm64

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./openapi.yaml

  LambdaPowertoolsLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs20.x
    Properties:
      LayerName: lambda-powertools-layer
      ContentUri: layers/lambda-powertools
      CompatibleRuntimes:
        - nodejs20.x

  AdditionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/addition
      Events:
        AdditionEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /addition
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole

  SubstractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/substraction
      Events:
        SubstractionEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /substraction
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  ApiURL:
    Description: API URL
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/api