name: Portman Tests

on:
  workflow_call:
    inputs:
      BASE_URL:
        required: true
        type: string

jobs:
  portman:
    name: Run Portman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test API
        env:
          BASE_URL: ${{ inputs.BASE_URL }}
        run: |
          npm ci
          npx @apideck/portman --cliOptionsFile portman/portman-cli.json --baseUrl ${{ inputs.BASE_URL }}