name: Deploy API

on:
  workflow_call:
    inputs:
      AWS_REGION:
        type: string
        required: true
      PIPELINE_EXECUTION_ROLE:
        type: string
        required: true
      CLOUDFORMATION_EXECUTION_ROLE:
        type: string
        required: true
      ARTIFACTS_BUCKET_NAME:
        type: string
        required: true
      STACK_NAME:
        type: string
        required: true
      TABLE_NAME:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy SAM Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.AWS_REGION }}
          role-to-assume: ${{ inputs.PIPELINE_EXECUTION_ROLE }}
          role-session-name: discovery-deploy
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Replace Variables in samconfig
        run: |
          npm i -g replace-in-files-cli
          replace-in-files --string='{{StackName}}' --replacement='${{ inputs.STACK_NAME }}' ./samconfig.ci.toml
          replace-in-files --string='{{TableName}}' --replacement='${{ inputs.TABLE_NAME }}' ./samconfig.ci.toml
          cat ./samconfig.ci.toml
      - name: SAM Build and Deploy
        run: |
          sam --info

          sam build --config-file samconfig.ci.toml

          sam deploy \
          --config-file samconfig.ci.toml \
          --config-env api \
          --s3-bucket ${{ inputs.ARTIFACTS_BUCKET_NAME }} \
          --no-fail-on-empty-changeset \
          --role-arn ${{ inputs.CLOUDFORMATION_EXECUTION_ROLE }}